language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt

script:
  - make test
  - make clean && make

after_script:
  - coveralls

sudo: false
